### ISSUE TITLE
Add list of dependencies, e.g. exiftool 

### ISSUE THREAD

**Issue by alvinsj** [rburns/photolog#2]
maybe documentation, or with an install script?

**Comment by rburns** [comment]
Difficult to do a cross-platform install script I guess. so probably documentation. But maybe it's possible to remove the exiftool dependency by using https://github.com/dberesford/exiv2node in it's place, or something similar.

As I understand it exiv2 isn't as full featured as exiftool (http://dev.exiv2.org/projects/exiv2/wiki/How_does_Exiv2_compare_to_Exiftool). Though, if it were featured enough for this use case, it may have the benefit of being quicker, in addition to being an easier to manage dependency.

did you come across any other undocumented dependencies?

**Comment by rburns** [comment]
addressed here b36afc899758443ff57821a0dfeae83b760dd4e4
